[package]
name = "freyacn_macros"
version = "0.0.0"
authors = ["Bright Madueke <maduekebright399@gmail.com>"]
description = "Helper macros for freyacn"
keywords = ["freya","freyacn", "proc_macro", "procmacro"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = { version = "2", features = ["full"] }

